Fixed issue #3 on gh, fixed ftconfig bugs (also oops)

diff --git a/extlib/bin/freetype-config b/extlib/bin/freetype-config
--- a/extlib/bin/freetype-config
+++ b/extlib/bin/freetype-config
@@ -1,4 +1,9 @@
 #!/bin/sh
+if test ! -f Makefile.onscripter; then
+    echo "freetype-config: error: run from incorrect directory"
+    exit 1
+fi
+
 if test "$1" = "--ftversion"; then
     echo "2.13.0"
 elif test "$1" = "--cflags"; then
